[workspace]
members = [
  "packages/testing",
  "packages/utils",
]

[workspace.package]
description = "Starkware Starknet contracts utils"
edition = "2024_07"
keywords = [
  "starkware",
  "starknet",
  "utils",
]
license-file = "LICENSE"
repository = "https://github.com/starkware-libs/starkware-starknet-utils"
version = "1.0.0"

[workspace.dependencies]
assert_macros = "2.17.0-rc.1"
openzeppelin = { git = "https://github.com/noa-starkware/cairo-contracts", rev = "d5f9f389c5c6fc91fe58eff8fc7ab83e5a100e05"}
snforge_std = { version = "0.55.0+nightly-2026-02-03", registry = "https://scarbs.dev/" }
starknet = "2.17.0-rc.1"

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[profile.dev.cairo]
inlining-strategy = "avoid"
panic-backtrace = true
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
