[package]
name = "contracts_commons"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true
openzeppelin_testing.workspace = true

[scripts]
test = "SNFORGE_BACKTRACE=1 snforge test"

[lib]

[[target.starknet-contract]]

[[test]]
name = "contracts_commons_unittest"

[tool.fmt]
sort-module-level-items = true
