use core::serde::Serde;
use openzeppelin::interfaces::accounts::ISRC6Dispatcher;
use openzeppelin::interfaces::src9::{ISRC9_V2Dispatcher, OutsideExecution};
use openzeppelin::interfaces::token::erc20::IERC20Dispatcher;
use snforge_std::cheatcodes::CheatSpan;
use snforge_std::{
    ContractClassTrait, DeclareResultTrait, EventSpyTrait, cheat_block_timestamp, cheat_chain_id,
    cheat_nonce, cheat_resource_bounds, cheat_tip, cheat_transaction_version,
};
use starknet::account::Call;
use starknet::secp256_trait::Signature;
use starknet::{ClassHash, ContractAddress, EthAddress, ResourcesBounds, SyscallResultTrait};
use starkware_accounts::interface::{IAccount712AdminDispatcher, IAccount712AdminDispatcherTrait};
use crate::test_helpers::event_helpers::get_event_by_selector;

// ================================
// Fixed addresses for deterministic signatures
// ================================
// These addresses are used with deploy_at to ensure signatures remain valid
// regardless of contract code changes.

/// Fixed account contract address for EFO tests.
/// All pre-computed signatures use this address in the domain separator.
pub const FIXED_ACCOUNT_ADDRESS: felt252 = 0x07120acc07120acc07120acc07120acc;

/// Fixed ERC20 mock address for EFO tests with calls.
/// All pre-computed signatures involving ERC20 calls use this address.
pub const FIXED_ERC20_ADDRESS: felt252 = 0x0e2c200e2c200e2c200e2c200e2c2000;

/// Protocol address (zero) used as caller for __execute__.
pub const PROTOCOL_ADDRESS: felt252 = 0;

/// Class hash of the RegisterInterfacesEIC contract, used as upgrade target in signing tests.
/// Must match FIXED_UPGRADE_TARGET_CLASS_HASH in generate_test_signatures.py.
/// Re-run generate_test_signatures.py after recompiling if this contract changes.
pub const FIXED_UPGRADE_TARGET_CLASS_HASH: felt252 =
    0x116b817c8fd4d03b340edb899d0c074b1c36ba9b643af1422bd5ed6ee0d555d;

/// Test Ethereum address corresponding to private key:
/// 0xa6d86467b6ec9e161649b27edfd8519e75a2e1cf5f4c309c628706e6999780e8
/// Address: 0xbF60187c5dFfA627249f1C3000A4168dbB9D7A1A
pub fn TEST_ETH_ADDRESS() -> EthAddress {
    0xbF60187c5dFfA627249f1C3000A4168dbB9D7A1A_felt252.try_into().unwrap()
}

/// Returns the ownership signature for TEST_ETH_ADDRESS.
/// This signature was generated by signing the OWNERSHIP_TRANSFER_MSG_HASH
/// (0x3ce976d55131cd0bdd49f20afbded052d8e907dc6034d95cdf117a8fd7752e3c)
/// with the test private key.
///
/// Values from: split_raw_eth_sig_to_felts output
/// '0xda47d5165a4577a024d18b8d61c5fe53 0xe994c0e202b390bddaffacf04bdea826
/// 0x46dd0af587023ccad738aa0a82b05f98 0x2e117624d8cc474d0641c3168944eb67 0x1'
pub fn get_ownership_signature() -> Signature {
    Signature {
        r: u256 {
            low: 0xda47d5165a4577a024d18b8d61c5fe53, high: 0xe994c0e202b390bddaffacf04bdea826,
        },
        s: u256 {
            low: 0x46dd0af587023ccad738aa0a82b05f98, high: 0x2e117624d8cc474d0641c3168944eb67,
        },
        y_parity: true // v % 2 == 0
    }
}

/// Returns an invalid signature for testing.
pub fn get_invalid_signature() -> Signature {
    Signature {
        r: u256 { low: 0x1234567890abcdef, high: 0xfedcba0987654321 },
        s: u256 { low: 0xabcdef1234567890, high: 0x1234567890abcdef },
        y_parity: false,
    }
}

/// Declare and deploy the StarknetEth712Account contract at FIXED_ACCOUNT_ADDRESS.
/// Returns the contract address and the class hash.
pub fn deploy_eth712_account() -> (ContractAddress, ClassHash) {
    let contract_class = snforge_std::declare("StarknetEth712Account")
        .unwrap_syscall()
        .contract_class();
    let fixed_address: ContractAddress = FIXED_ACCOUNT_ADDRESS.try_into().unwrap();
    let (contract_address, _) = contract_class.deploy_at(@array![], fixed_address).unwrap_syscall();
    (contract_address, *contract_class.class_hash)
}

/// Declare the RegisterInterfacesEIC contract and return its class hash.
pub fn declare_register_interfaces_eic() -> ClassHash {
    *snforge_std::declare("RegisterInterfacesEIC").unwrap_syscall().contract_class().class_hash
}

/// Deploy, initialize, and return an ISRC6Dispatcher for the account.
pub fn setup_initialized_account() -> ISRC6Dispatcher {
    let (account_address, _) = deploy_eth712_account();
    let account_contract = IAccount712AdminDispatcher { contract_address: account_address };
    account_contract.initialize(TEST_ETH_ADDRESS(), get_ownership_signature());
    ISRC6Dispatcher { contract_address: account_address }
}

/// Assert that an "Upgraded" event was emitted from the expected address with the expected class
/// hash.
pub fn assert_upgraded_event(
    ref spy: snforge_std::EventSpy, account_address: ContractAddress, expected_class_hash: felt252,
) {
    let events = spy.get_events();
    let event_option = get_event_by_selector(events.events.span(), selector!("Upgraded"));
    assert!(event_option.is_some(), "Upgraded event not found");
    let (from, event) = event_option.unwrap();
    assert!(*from == account_address, "Event from wrong address");
    assert!(*event.data.at(0) == expected_class_hash, "Wrong class hash in event");
}

// ================================
// Execute-from-outside (EFO) test setup helpers
// ================================

/// Setup an initialized account with configurable timestamp for EFO tests.
/// Returns src9_dispatcher (use src9.contract_address if account address is needed).
pub fn setup_efo_test_with_timestamp(timestamp: u64) -> ISRC9_V2Dispatcher {
    let (account_address, _) = deploy_eth712_account();
    let account_contract = IAccount712AdminDispatcher { contract_address: account_address };
    account_contract.initialize(TEST_ETH_ADDRESS(), get_ownership_signature());
    cheat_block_timestamp(account_address, timestamp, CheatSpan::Indefinite);
    cheat_chain_id(account_address, 'SN_MAIN', CheatSpan::Indefinite);
    ISRC9_V2Dispatcher { contract_address: account_address }
}

/// Setup an initialized account with default TEST_TIMESTAMP for EFO tests.
/// Returns src9_dispatcher (use src9.contract_address if account address is needed).
pub fn setup_efo_test() -> ISRC9_V2Dispatcher {
    setup_efo_test_with_timestamp(TEST_TIMESTAMP)
}

/// Setup an initialized account with ERC20 mock for EFO tests.
/// Returns (src9_dispatcher, token_address, erc20_dispatcher).
pub fn setup_efo_test_with_erc20() -> (ISRC9_V2Dispatcher, ContractAddress, IERC20Dispatcher) {
    let src9 = setup_efo_test();
    let (token_address, token) = deploy_mock_erc20(src9.contract_address);
    (src9, token_address, token)
}

// ================================
// __validate__ / __execute__ test setup
// ================================

/// Fixed resource bounds for __validate__ tests.
/// Must match VALIDATE_RESOURCE_BOUNDS in generate_test_signatures.py.
pub fn validate_resource_bounds() -> Span<ResourcesBounds> {
    array![
        ResourcesBounds { resource: 'L1_GAS', max_amount: 100, max_price_per_unit: 1000 },
        ResourcesBounds { resource: 'L2_GAS', max_amount: 200, max_price_per_unit: 2000 },
        ResourcesBounds { resource: 'L1_DATA', max_amount: 300, max_price_per_unit: 3000 },
    ]
        .span()
}

/// Setup an initialized account with all tx_info fields cheated for __validate__/__execute__ tests.
/// Cheats: chain_id, version, nonce, resource_bounds, tip.
/// Signature must be cheated separately per test.
/// Returns (src6_dispatcher, account_address).
pub fn setup_validate_test() -> (ISRC6Dispatcher, ContractAddress) {
    let (account_address, _) = deploy_eth712_account();
    let account_contract = IAccount712AdminDispatcher { contract_address: account_address };
    account_contract.initialize(TEST_ETH_ADDRESS(), get_ownership_signature());

    cheat_chain_id(account_address, 'SN_MAIN', CheatSpan::Indefinite);
    cheat_transaction_version(account_address, 3, CheatSpan::Indefinite);
    cheat_nonce(account_address, VALIDATE_NONCE_EMPTY, CheatSpan::Indefinite);
    cheat_resource_bounds(account_address, validate_resource_bounds(), CheatSpan::Indefinite);
    cheat_tip(account_address, 0, CheatSpan::Indefinite);

    (ISRC6Dispatcher { contract_address: account_address }, account_address)
}

// ================================
// OutsideExecution test fixtures
// ================================

/// Fixed timestamps for testing execute_from_outside_v2.
pub const EXECUTE_AFTER: u64 = 1000;
pub const EXECUTE_BEFORE: u64 = 3000;
pub const TEST_TIMESTAMP: u64 = 2000;
pub const TEST_NONCE: felt252 = 1;

/// ANY_CALLER constant from SNIP-9.
pub const ANY_CALLER: felt252 = 'ANY_CALLER';

/// Returns a test OutsideExecution with fixed values and empty calls.
/// Using empty calls to avoid ENTRYPOINT_NOT_FOUND errors during testing.
pub fn get_test_outside_execution() -> OutsideExecution {
    OutsideExecution {
        caller: ANY_CALLER.try_into().unwrap(),
        nonce: TEST_NONCE,
        execute_after: EXECUTE_AFTER,
        execute_before: EXECUTE_BEFORE,
        calls: array![].span() // Empty calls for testing
    }
}

/// Returns an invalid signature for testing signature validation.
pub fn get_invalid_outside_execution_signature() -> Array<felt252> {
    array![
        0x1234567890abcdef1234567890abcdef, // r_high (invalid)
        0xfedcba0987654321fedcba0987654321, // r_low
        0xabcdef1234567890abcdef1234567890, // s_high
        0x0987654321fedcba0987654321fedcba, // s_low
        27, // v
        1 // chain_id
    ]
}

// ================================
// ERC20 Mock helpers for execute_from_outside tests
// ================================

/// Initial supply for mock ERC20 token.
pub const MOCK_ERC20_INITIAL_SUPPLY: u256 = 1000_u256;

/// Deploy a mock ERC20 token at FIXED_ERC20_ADDRESS with initial supply minted to the owner.
/// Returns (token_address, dispatcher).
pub fn deploy_mock_erc20(owner: ContractAddress) -> (ContractAddress, IERC20Dispatcher) {
    let contract_class = snforge_std::declare("DualCaseERC20Mock")
        .unwrap_syscall()
        .contract_class();

    // Constructor: (name, symbol, decimals, initial_supply, recipient)
    let mut calldata: Array<felt252> = array![];
    let name: ByteArray = "MockToken";
    name.serialize(ref calldata);
    let symbol: ByteArray = "MTK";
    symbol.serialize(ref calldata);
    let decimals: u8 = 18;
    decimals.serialize(ref calldata);
    MOCK_ERC20_INITIAL_SUPPLY.serialize(ref calldata);
    owner.serialize(ref calldata);

    let fixed_address: ContractAddress = FIXED_ERC20_ADDRESS.try_into().unwrap();
    let (token_address, _) = contract_class.deploy_at(@calldata, fixed_address).unwrap_syscall();
    let dispatcher = IERC20Dispatcher { contract_address: token_address };
    (token_address, dispatcher)
}

/// Fixed spender address used in pre-computed approve call signatures.
pub const APPROVE_SPENDER: felt252 = 0x1234;

/// Fixed approve amount used in pre-computed approve call signatures.
pub const APPROVE_AMOUNT: u256 = 500_u256;

/// Returns the fixture approve Call matching pre-computed signatures.
pub fn get_approve_call() -> Call {
    let token_address: ContractAddress = FIXED_ERC20_ADDRESS.try_into().unwrap();
    let spender: ContractAddress = APPROVE_SPENDER.try_into().unwrap();
    Call {
        to: token_address,
        selector: selector!("approve"),
        calldata: array![spender.into(), APPROVE_AMOUNT.low.into(), APPROVE_AMOUNT.high.into()]
            .span(),
    }
}

/// Build a transfer Call for ERC20.
pub fn build_transfer_call(
    token_address: ContractAddress, recipient: ContractAddress, amount: u256,
) -> Call {
    Call {
        to: token_address,
        selector: selector!("transfer"),
        calldata: array![recipient.into(), amount.low.into(), amount.high.into()].span(),
    }
}

/// EFO nonces for different test scenarios (to avoid conflicts).
pub const NONCE_SINGLE_CALL: felt252 = 100;
pub const NONCE_MULTI_CALL: felt252 = 101;
pub const NONCE_ATOMICITY: felt252 = 102;
pub const NONCE_SPECIFIC_CALLER: felt252 = 103;
pub const NONCE_EFO_UPGRADE: felt252 = 200;

/// __validate__ nonces matching generate_test_signatures.py.
pub const VALIDATE_NONCE_EMPTY: felt252 = 0;
pub const VALIDATE_NONCE_WITH_CALLS: felt252 = 1;
pub const VALIDATE_NONCE_UPGRADE: felt252 = 2;

/// Specific caller address for testing non-ANY_CALLER scenarios.
pub const SPECIFIC_CALLER: felt252 = 0xCAFE;

/// Build OutsideExecution with specified calls (uses ANY_CALLER).
pub fn build_outside_execution_with_calls(calls: Span<Call>, nonce: felt252) -> OutsideExecution {
    OutsideExecution {
        caller: ANY_CALLER.try_into().unwrap(),
        nonce,
        execute_after: EXECUTE_AFTER,
        execute_before: EXECUTE_BEFORE,
        calls,
    }
}

/// Build OutsideExecution with a specific caller (not ANY_CALLER).
pub fn build_outside_execution_with_specific_caller(
    nonce: felt252, caller: ContractAddress,
) -> OutsideExecution {
    OutsideExecution {
        caller,
        nonce,
        execute_after: EXECUTE_AFTER,
        execute_before: EXECUTE_BEFORE,
        calls: array![].span(),
    }
}

// GENERATED-SIGNATURES-START (by scripts/generate_test_signatures.py -- do not edit manually)

/// EFO signature: empty calls, nonce=1, chain_id=1.
pub fn get_outside_execution_signature() -> Array<felt252> {
    array![
        0x7ffb66a7163f54ab83a435079d74198d, 0x5ceb653460c57bda62685e60d4b67dc9,
        0x7c07a7689645c4ec1775cd794e6a6bdc, 0xfaecbd63a4629b6e3d43e88568000326, 27, 1,
    ]
}

/// EFO signature: empty calls, nonce=1, chain_id=2.
pub fn get_signature_evm_chain_id_2() -> Array<felt252> {
    array![
        0x18a89b5013e9920a4a6a7f68a96e7ae4, 0xaedf914a0262920a3587429fbe9fc6a1,
        0x71d90cd8ba933785e1f9310f75527dc4, 0x4af653a5e6924e30858c257ad6dc36bd, 28, 2,
    ]
}

/// EFO signature signed with SN_SEPOLIA domain (fails against SN_MAIN).
pub fn get_signature_wrong_sn_chain_name() -> Array<felt252> {
    array![
        0x17ffed4d61c7339e41abad0f195e514f, 0x12fc8d4f5d27d5e2465955842e13c655,
        0x68f5bb339084078d1a34bbed9c5a3c52, 0xaf67088632eee196f68414a550359178, 28, 1,
    ]
}

/// EFO signature signed with wrong contract address (domain mismatch).
pub fn get_signature_wrong_contract_address() -> Array<felt252> {
    array![
        0x060836bf3cbe32460860af643ccd889d, 0x31673c0a6f4686d5cd41c9003f390a81,
        0x1d39adf7397f46f16ca26ee7979844eb, 0xd88fdcb5a1f5602ad4d95c8cf0ada12a, 28, 1,
    ]
}

/// EFO signature: approve(0x1234, 500), nonce=100.
pub fn get_single_call_approve_signature() -> Array<felt252> {
    array![
        0x964d17d195fc47aba6702c78cbb8efc2, 0x9f154a7cb4f786c87247bb20aaef2800,
        0x4fb1263e4d824bf8886d1809927e10b3, 0x0630802ef735ec030b55521174002356, 27, 1,
    ]
}

/// EFO signature: approve(500) + transfer(100), nonce=101.
pub fn get_multi_call_signature() -> Array<felt252> {
    array![
        0xb914302a1acb85e3f6b155625fea3dad, 0x9e0069305c9c2cc94ec6180529e265ce,
        0x2fe4565842cb96b600ff4c58e45b55e6, 0xd55a87fddd1cc8e553dca9a7456d465e, 27, 1,
    ]
}

/// EFO signature: approve(500) + transfer(1001, fails), nonce=102.
pub fn get_atomicity_test_signature() -> Array<felt252> {
    array![
        0x1609bcddfc92674937de1c281392b0ea, 0xb96e843d8911d3e009ce55aecdca7ab4,
        0x110742199fc56f913d2eeab31f8c5251, 0x53c98399effa51de52da5a029b57e578, 28, 1,
    ]
}

/// EFO signature: specific caller=0xCAFE, nonce=103, empty calls.
pub fn get_specific_caller_signature() -> Array<felt252> {
    array![
        0xa9855b38d21f9f8aea399f9a1d187319, 0xc8f9e2b75f011d953bb7206bd62fd0c6,
        0x640bd21aa3ccccfa412427e8a0ceeed3, 0xee65414d86523ac9b8772e99468d7e80, 27, 1,
    ]
}

/// __validate__ signature: empty calls, nonce=0.
pub fn get_validate_empty_calls_signature() -> Array<felt252> {
    array![
        0x0c7ab95484df32ee1f457501214b5c51, 0x0fd461a1c92f777d97545e640f893731,
        0x78afd3e69cdf4b6c57b49b8fd719ff0e, 0x24553f8f1b1cdb5121ef8641a2dbcab5, 28, 1,
    ]
}

/// __validate__ signature: approve(0x1234, 500), nonce=1.
pub fn get_validate_with_approve_signature() -> Array<felt252> {
    array![
        0xfdf4a332c8f6bded4b9670e59d8d90e6, 0xb1c10fd29b606f3522c62fc237d5ec1f,
        0x7a4518381cf3240b4b96169848677726, 0xf642df7a6d69205f1f390f6205adab44, 27, 1,
    ]
}

/// __validate__ signature signed with SN_SEPOLIA domain (fails against SN_MAIN).
pub fn get_validate_wrong_chain_signature() -> Array<felt252> {
    array![
        0x455a3be29526aebe2731210b357f666b, 0x1ca8edb5a5e21e7f16f9b2d663fe0141,
        0x629a920e9971312499308cbadf8d0d25, 0xb406cd3e690bead8d1923dfd93a5a466, 28, 1,
    ]
}

/// CallSet signature: empty calls.
pub fn get_call_set_empty_calls_signature() -> Array<felt252> {
    array![
        0xae3eb6ab4fdb8a51ceeb5c40e51be3ca, 0xf74187ba31cd3f349f8109bbee43b6b0,
        0x005515473f842966cb900e454245deb5, 0xaa9326d942984ea22e545c9ab2dcc3b3, 28, 1,
    ]
}

/// CallSet signature: approve(0x1234, 500).
pub fn get_call_set_with_approve_signature() -> Array<felt252> {
    array![
        0x278778484aaed07e7aedfde9d083a8ef, 0x887154c31481c204416d3d323bcb108c,
        0x25eed52af478ac87dcf1dd528475af22, 0xfd39cb55c54d25904c96ff0d079b89b6, 28, 1,
    ]
}

/// CallSet signature: approve(0x1234, 500) with additional_data=[10, 11].
pub fn get_call_set_with_additional_data_signature() -> Array<felt252> {
    array![
        0xcefcd06a012378cceb1bfa5b2831ef0d, 0xa5424ce854f5a39bf61df96013f21f94,
        0x390242713792f83e134ccabc69a153ca, 0x8916d2267a20441a5a60b0b565735d03, 27, 1,
    ]
}

/// EFO signature: upgrade(FIXED_UPGRADE_TARGET_CLASS_HASH, None), nonce=200.
pub fn get_efo_upgrade_signature() -> Array<felt252> {
    array![
        0x0310b2e62cbb8c63ac5cbb9e78f1712e, 0xc9d348904fd30995b7876a4fd585a067,
        0x2bbe26757cf66b816f298d5fe559a2e5, 0x123af974f819a5c9238602f456cc9d6a, 27, 1,
    ]
}

/// __validate__ signature: upgrade(FIXED_UPGRADE_TARGET_CLASS_HASH, None), nonce=2.
pub fn get_validate_upgrade_signature() -> Array<felt252> {
    array![
        0x2aa44a28b178a7b635af3c7f13377c2c, 0xbb2407616673c54e374224a19fc53c79,
        0x08cfcf1f2931d92f10c78f3b02572cfa, 0xcd3c2665bcc50041a268174db3563fb2, 28, 1,
    ]
}
// GENERATED-SIGNATURES-END


