[package]
name = "starkware_utils_testing"
readme = "README.md"
version = "1.0.0"
keywords = [
    "starkware",
    "starknet",
    "utils",
    "testing"
]
edition.workspace = true
description.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
snforge_std.workspace = true
assert_macros.workspace = true
openzeppelin_testing.workspace = true
starkware_utils =  {path = "../../"}

[dev-dependencies]

[scripts]
test = "SNFORGE_BACKTRACE=1 snforge test"

[lib]

[[target.starknet-contract]]

[tool]
fmt.workspace = true
scarb.workspace = true

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"
