[package]
name = "starkware_utils_testing"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.0"
openzeppelin = "1.0.0"
snforge_std = "0.34.0"
assert_macros = "2.11.0"
openzeppelin_testing = "1.0.0"
starkware_utils =  {path = "../../"}

[dev-dependencies]
snforge_scarb_plugin = "0.34.0"

[scripts]
test = "SNFORGE_BACKTRACE=1 snforge test"

[lib]

[[target.starknet-contract]]

[tool.fmt]
sort-module-level-items = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"
