[package]
name = "starkware_utils"
readme = "README.md"
version.workspace = true
keywords.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true
openzeppelin_testing.workspace = true
starkware_utils_testing = { path = "../testing" }

[scripts]
test = "SNFORGE_BACKTRACE=1 snforge test"

[lib]

[[target.starknet-contract]]

[[test]]
name = "starkware_utils_unittest"

[tool]
fmt.workspace = true
scarb.workspace = true

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"
