name: Pull Request Integration

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.9.2"

      - name: Check formatting
        run: |
          scarb fmt --check
          exit $?

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/setup-snfoundry@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.9.2"

      - name: Run test
        run: scarb test

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/setup-snfoundry@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.9.2"

      - name: Install cairo-coverage
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/cairo-coverage/main/scripts/install.sh | sh

      - name: Add necessary debug flags
        run: printf "\n[profile.dev.cairo]\nunstable-add-statements-functions-debug-info = true\nunstable-add-statements-code-locations-debug-info = true\ninlining-strategy = \"avoid\"\n" >> Scarb.toml

      - name: Run coverage
        run: snforge test --coverage

      - uses: codecov/codecov-action@v5.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage.lcov
          fail_ci_if_error: true
