name: Pull Request Integration

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install scarb
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/scarb/main/install.sh | sh
          export PATH="$HOME/.local/bin:$PATH"

      - name: Format code
        run: scarb fmt

      - name: Check if there's a difference
        run: |
          if [ -n "$(git diff)" ]; then
            echo "PR is not formatted."
            exit 1
          fi

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install scarb
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/scarb/main/install.sh | sh
          export PATH="$HOME/.local/bin:$PATH"

      - name: Run test
        run: scarb test

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/setup-snfoundry@v3
      - name: Install scarb
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/scarb/main/install.sh | sh
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install cairo-coverage
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/cairo-coverage/main/scripts/install.sh | sh

      - name: Add necessary debug flags
        run: printf "\n[profile.dev.cairo]\nunstable-add-statements-functions-debug-info = true\nunstable-add-statements-code-locations-debug-info = true\ninlining-strategy = \"avoid\"\n" >> Scarb.toml

      - name: Run coverage
        run: snforge test --coverage

      - uses: codecov/codecov-action@v5.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage.lcov
          fail_ci_if_error: true
