name: Pull Request Integration

on:
  pull_request:
    branches:
      - arad/ci-coverage

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install scarb
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/scarb/main/install.sh | sh
          export PATH="$HOME/.local/bin:$PATH"

      - name: Format code
        run: scarb fmt

      - name: Check if there's a difference
        run: |
          if [ "git diff --exit-code" ]; then
            echo "PR is not formatted."
            exit 1
          fi

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install scarb
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/scarb/main/install.sh | sh
          export PATH="$HOME/.local/bin:$PATH"

      - name: Run test
        run: scarb test

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: codecov/codecov-action@v5.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage.lcov

      # - name: Install scarb
      #   run: |
      #     curl -L https://raw.githubusercontent.com/software-mansion/scarb/main/install.sh | sh
      #     export PATH="$HOME/.local/bin:$PATH"
      #
      # - name: Install cairo-coverage
      #   run: |
      #     curl -L https://raw.githubusercontent.com/software-mansion/cairo-coverage/main/scripts/install.sh | sh

      - name: Install scarb
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.starkup.dev | sh
          export PATH="$HOME/.local/bin:$PATH"

      - name: Add necessary debug flags
        run: echo "
          [profile.dev.cairo]
          unstable-add-statements-functions-debug-info = true
          unstable-add-statements-code-locations-debug-info = true
          inlining-strategy = "avoid"
          " >> Cargo.toml

      - name: Run coverage
        run: snforge test --coverage
