name: Pull Request Integration

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install scarb
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/scarb/main/install.sh | sh
          export PATH="$HOME/.local/bin:$PATH"

      - name: Format code
        run: scarb fmt

      - name: Check if there's a difference
        run: |
          if [ -n "$(git diff)" ]; then
            echo "PR is not formatted."
            exit 1
          fi

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install scarb
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/scarb/main/install.sh | sh
          export PATH="$HOME/.local/bin:$PATH"

      - name: Run test
        run: scarb test
