name: starkware_utils publish

on:
  push:
    tags:
      - 'release-v*.*.*'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      SCARB_REGISTRY_AUTH_TOKEN: ${{ secrets.SCARB_REGISTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.11.2"

      - name: Extract current versions
        run: |
          CURRENT_VERSION=$(grep '^version = ' Scarb.toml | sed 's/version = "\(.*\)"/\1/')
          {
            echo "CURRENT_VERSION=$CURRENT_VERSION"
          } >> "$GITHUB_ENV"
        
      - name: Extract new version number
        run: echo "NEW_VERSION=${GITHUB_REF#refs/tags/release-v}" >> $GITHUB_OUTPUT

      - name: Replace version in files
        run: |
          echo "Current version: $CURRENT_VERSION"
          echo "New version: $NEW_VERSION"
          ESCAPED_CURRENT_VERSION="${CURRENT_VERSION//\./\\.}"
          find . -type f -not -path '*/\.*' \
            -not -path './packages/testing/*' \
            -exec sed -i "s/$ESCAPED_CURRENT_VERSION/$NEW_VERSION/g" {} +
          
      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump version to ${{ env.NEW_VERSION }}
        
      - name: Publish Package
        run: scarb publish -p starkware_utils
