name: starkware_utils publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    # Only run if the PR was merged and had the 'release' label
    if: >
      github.event.pull_request.merged == true && 
      contains(fromJson('["' + join(github.event.pull_request.labels.*.name, '","') + '"]'), 'release')

    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      SCARB_REGISTRY_AUTH_TOKEN: ${{ secrets.SCARB_REGISTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.11.3"

      - name: Extract publish version
        run: |
          CURRENT_VERSION=$(grep '^version = ' Scarb.toml | sed 's/version = "\(.*\)"/\1/')
          {
            echo "CURRENT_VERSION=$CURRENT_VERSION"
          } >> "$GITHUB_ENV"  
        
      - name: Publish Package
        run: scarb publish -p starkware_utils

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ env.CURRENT_VERSION }}
          tag_name: v${{ env.CURRENT_VERSION }}
