name: starkware_utils publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    # Only run if the PR was merged and had the 'release' label
    if: github.event.pull_request.merged == true && github.event.pull_request.labels.*.name == 'release'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      SCARB_REGISTRY_AUTH_TOKEN: ${{ secrets.SCARB_REGISTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.11.3"
        
      - name: Publish Package
        run: scarb publish -p starkware_utils
